# Name(s)
Alberto Rodriguez

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

In [1]:
import numpy as np
import math
import pandas as pd

## Exercise 1

In [2]:
a = np.full(shape=(6,4), fill_value=2)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 2

In [3]:
b = np.full(shape=(6,4), fill_value=1)
np.fill_diagonal(b, 3)
b

array([[3, 1, 1, 1],
       [1, 3, 1, 1],
       [1, 1, 3, 1],
       [1, 1, 1, 3],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Exercise 3

In [4]:
a * b

array([[6, 2, 2, 2],
       [2, 6, 2, 2],
       [2, 2, 6, 2],
       [2, 2, 2, 6],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [5]:
# np.dot(a, b) breaks

Literally multiplying each (row,col) value within their respective matrices does work (because they are the same shape). However, this does not work for the dot product because the b's rows does not match a's columns.

## Exercise 4

In [6]:
print("Shape of Matrices: ", a.transpose().shape, "x", b.shape)
answer = np.dot(a.transpose(), b)
print("Resulting Shape: ", answer.shape)
answer

Shape of Matrices:  (4, 6) x (6, 4)
Resulting Shape:  (4, 4)


array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [7]:
print("Shape of Matrices: ", a.shape, "x", b.transpose().shape)
answer = np.dot(a, b.transpose())
print("Resulting Shape: ", answer.shape)
answer

Shape of Matrices:  (6, 4) x (4, 6)
Resulting Shape:  (6, 6)


array([[12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8]])

The calculations above are valid because a's columns are adjusted to match b's rows, and vica versa. Although changing a or b both allow for the dot product to work, they result in different shapes since the number of a's rows is preseved as well as b's columns.

## Exercise 5

In [8]:
def totallyNotAFunction():
    print("Just kidding this is a function")
totallyNotAFunction()

Just kidding this is a function


## Exercise 6

In [9]:
def randomArrayStats():
    arr_len = np.random.randint(low=1, high=100, size=1)[0]
    arr = np.random.rand(arr_len, 1)
    print("Sum: ", arr.sum())
    print("Mean: ", arr.mean())
    print("Median: ", np.median(arr))
randomArrayStats()

Sum:  38.55439656281519
Mean:  0.47017556783920966
Median:  0.4512371376897376


## Exercise 7

In [10]:
def count_ones_loop(arr):
    count = 0
    for value in arr:
        if value == 1:
            count = count + 1
    return count
assert count_ones_loop([1, 2, 3, 1]) == 2

def count_ones_where(arr_like):
    arr = np.array(arr_like)
    return np.where(arr==1, arr, 0).sum()
assert count_ones_where([1, 2, 3, 1]) == 2, "Oh no"
assert count_ones_where([2, 3, 4]) == 0, "Oh no x2"

## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [11]:
a_np = np.full(shape=(6,4), fill_value=2)
a = pd.DataFrame(a_np)
a

0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [12]:
b_np = np.full(shape=(6,4), fill_value=1)
np.fill_diagonal(b_np, 3)
b = pd.DataFrame(b_np)
b

0  1  2  3
0  3  1  1  1
1  1  3  1  1
2  1  1  3  1
3  1  1  1  3
4  1  1  1  1
5  1  1  1  1

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [13]:
a * b

0  1  2  3
0  6  2  2  2
1  2  6  2  2
2  2  2  6  2
3  2  2  2  6
4  2  2  2  2
5  2  2  2  2

In [14]:
# np.dot(a, b)

The line above does not work for the same reasons as before, the shapes do not satisfy the requirements for the dot product operation.

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [15]:
def count_ones_loop(df):
    count = 0
    for row_index, columns in df.iterrows():
        for col_index in columns:
            if df[col_index][row_index] == 1:
                count = count + 1
    return count

assert count_ones_loop(b) == 20
assert count_ones_loop(a) == 0
    
def count_ones_where(df):
    return df.where(df == 1, 0).sum().sum()

assert count_ones_where(b) == 20
assert count_ones_where(a) == 0, count_ones_where(a)

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [16]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df.head(1)

pclass  survived                           name     sex   age  sibsp  \
0       1         1  Allen, Miss. Elisabeth Walton  female  29.0      0   

   parch ticket      fare cabin embarked boat  body     home.dest  
0      0  24160  211.3375    B5        S    2   NaN  St Louis, MO

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [17]:
titanic_df["name"]

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [18]:
titanic_df.set_index('sex',inplace=True)

titanic_df.loc["female"] is how one would use the new index to locate the female passengers.

In [19]:
print("Number of female passengers: ", len(titanic_df.loc["female"]))

Number of female passengers:  466


## Exercise 14
How do you reset the index?

In [20]:
titanic_df.reset_index(inplace=True)

In [21]:
titanic_df.head()

sex  pclass  survived                                             name  \
0  female       1         1                    Allen, Miss. Elisabeth Walton   
1    male       1         1                   Allison, Master. Hudson Trevor   
2  female       1         0                     Allison, Miss. Helen Loraine   
3    male       1         0             Allison, Mr. Hudson Joshua Creighton   
4  female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON